"""
Repository Interfaces
=====================

Module path:
    src/domain/repositories.py

Summary:
    Defines the repository interfaces (ports) for all aggregate roots and
    domain entities used by the application layer.

"""

from typing import Protocol, List, Optional
from domain.entities import Task, User, Team, Submission, SpeedTaskSession
from domain.config import (
    LogChannel, HostRole, SubmitterRole,
    SeekingChannel, TasksChannel, AnnouncementsChannel,
    SpeedTaskLength, SpeedTaskDesc,
    SpeedTaskReminders, ReminderPings, GuildConfig, SubmissionChannel,
)

class TaskRepository(Protocol):
    async def add(self, task: Task) -> None: ...
    async def get_last_task(self) -> Optional[Task]: ...
    async def get_by_id(self, id: int) -> Optional[Task]: ...
    async def get_active(self) -> Optional[Task]: ...
    async def save(self, task: Task) -> None: ...

class SpeedTaskRepository(Protocol):
    async def add(self, sess: SpeedTaskSession) -> None: ...
    async def get_by_user(self, user_id: int) -> Optional[SpeedTaskSession]: ...
    async def list_active_sessions(self) -> list[SpeedTaskSession]: ...
    async def expire_session(self, user_discord_id: int) -> SpeedTaskSession: ...
    async def clear_all(self) -> None: ...
    async def save(self, session_obj: SpeedTaskSession) -> None: ...

class UserRepository(Protocol):
    async def add(self, user: User) -> None: ...
    async def get_by_discord_id(self, discord_id: int) -> Optional[User]: ...
    async def save(self, user: User) -> None: ...

class SubmissionRepository(Protocol):
    async def add(self, sub: Submission) -> None: ...
    async def remove_user_submissions(self, task_id: int, user_id: int) -> None: ...
    async def remove_team_submissions(self, task_id: int, team_id: int) -> None: ...
    async def get_submission_by_user(self, task_id: int, user_id: int) -> Optional[Submission]: ...
    async def get_submission_by_team(self, task_id: int, team_id: int) -> Optional[Submission]: ...
    async def get_submissions(self, task_id: int) -> List[Submission]: ...
    async def clear_all(self) -> None: ...            # clear submission list
    async def save(self, sub: Submission) -> None: ...







class TeamRepository(Protocol):
    async def add(self, team: Team) -> None: ...
    async def get_by_id(self, id: int) -> Optional[Team]: ...
    async def get_by_member(self, user_id: int) -> Optional[Team]: ...
    async def get_teams(self) -> Optional[List[Team]]: ...
    async def save(self, team: Team) -> None: ...
    async def remove(self, team_id: int) -> None: ...
    async def clear_all(self) -> None: ...



class ConfigRepository(Protocol):
    # LogChannel
    async def get_log_channel(self, comp: str) -> Optional[LogChannel]: ...
    async def save_log_channel(self, cfg: LogChannel) -> None: ...

    # HostRole
    async def get_host_role(self, comp: str) -> Optional[HostRole]: ...
    async def save_host_role(self, cfg: HostRole) -> None: ...

    # SubmitterRole
    async def get_submitter_role(self, comp: str) -> Optional[SubmitterRole]: ...
    async def save_submitter_role(self, cfg: SubmitterRole) -> None: ...

    # SubmissionChannel
    async def get_submission_channel(self, comp: str) -> Optional[SubmissionChannel]: ...
    async def save_submission_channel(self, cfg: SubmissionChannel) -> None: ...

    # SeekingChannel
    async def get_seeking_channel(self, comp: str) -> Optional[SeekingChannel]: ...
    async def save_seeking_channel(self, cfg: SeekingChannel) -> None: ...

    # TasksChannel
    async def get_tasks_channel(self, comp: str) -> Optional[TasksChannel]: ...
    async def save_tasks_channel(self, cfg: TasksChannel) -> None: ...

    # AnnouncementsChannel
    async def get_announcements_channel(self, comp: str) -> Optional[AnnouncementsChannel]: ...
    async def save_announcements_channel(self, cfg: AnnouncementsChannel) -> None: ...

    # SpeedTaskLength
    async def get_speed_task_length(self, comp: str) -> Optional[SpeedTaskLength]: ...
    async def save_speed_task_length(self, cfg: SpeedTaskLength) -> None: ...

    # SpeedTaskDesc
    async def get_speed_task_desc(self, comp: str) -> Optional[SpeedTaskDesc]: ...
    async def save_speed_task_desc(self, cfg: SpeedTaskDesc) -> None: ...
    async def clear(self) -> None: ...

    # SpeedTaskReminders
    async def get_speed_task_reminders(self, comp: str) -> Optional[SpeedTaskReminders]: ...
    async def save_speed_task_reminders(self, cfg: SpeedTaskReminders) -> None: ...

    # ReminderPings
    async def get_reminder_pings(self, comp: str) -> Optional[ReminderPings]: ...
    async def save_reminder_pings(self, cfg: ReminderPings) -> None: ...

    # Map guild to comp
    async def get_guild_config(self, guild_id: int) -> Optional[GuildConfig]: ...

    async def save_guild_config(self, cfg: GuildConfig) -> None: ...

