name: Pylint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.13
        cache: pip
        cache-dependency-path: 'requirements.txt'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        dirs="./main.py ./video.py api commands events"
        echo "Checking for errors..." & find $dirs -regex '.*\.py' | xargs pylint -E
        echo "Linting..." & find $dirs -regex '.*\.py' | xargs pylint --exit-zero
